name: Tests

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Creating conda environment for ${{ matrix.python-version }}
      run: |
        conda create -n test -y make

    - name: Install dependencies
      run: |
        conda run -n test python3 -m pip install -e .[tests]

    - name: Linting
      run: |
        conda run -n test make lint

  tests:

    runs-on: ubuntu-latest
    strategy:
        max-parallel: 5
        matrix:
          python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Creating conda environment for ${{ matrix.python-version }}
      run: |
        conda create -n test -y python=${{matrix.python-version}} netcdf4 zarr make

    - name: Install dependencies
      run: |
        conda run -n test python3 -m pip install -e .[tests] #--constraint .github/dependabot/constraints.txt

    - name: Test with pytest
      run: |
        conda run -n test make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

    -
        name: Gather dependabot metadata
        id: matadata
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      -
        name: Approve dependabots PR
        if: ${{ github.actor == 'dependabot[bot]' }}
        run: gh pr review --approve "${{github.event.pull_request.html_url}}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      -
        name: Merge dependabots PR
        if: ${{ github.actor == 'dependabot[bot]' }}
        run: gh pr merge --auto --merge "${{github.event.pull_request.html_url}}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
